[package]
name = "ipify-rs"
version = "0.5.0"
edition = "2021"
authors = ["Ollivier Robert <roberto@keltia.net>"]
keywords = ["ipify", "api", "client"]
repository = "https://github.com/keltia/ipify-rs"
license = "MIT"
readme = "README.md"
description = "Rust crate for the ipify.org API."
documentation = "https://docs.rs/ipify-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
log = "0.4"
reqwest = { version = "0.11.6", features = ["blocking"] }
stderrlog = "0.5.1"
